package com.htc.hibernate.pojo;
// Generated 16 Aug, 2015 3:28:11 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * EnergyState generated by hbm2java
 */
public class EnergyState implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int id;
	private String state;
	private String color;
	private Set<?> holonObjects = new HashSet<Object>(0);

	public EnergyState() {
	}

	public EnergyState(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set<?> getHolonObjects() {
		return this.holonObjects;
	}

	public void setHolonObjects(Set<?> holonObjects) {
		this.holonObjects = holonObjects;
	}

}
