package com.htc.hibernate.pojo;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
/**
 * HolonObject generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class HolonObject implements java.io.Serializable, Comparable {
	private static final long serialVersionUID = 1L;
	private int id;
	private EnergyState energyState;
	private Holon holon;
	private HolonObjectType holonObjectType;
	private LatLng latLngByNeLocation;
	private LatLng latLngBySwLocation;
	private Boolean lineConnectedState;
	private Integer consumption;
	private Boolean canCommunicate;
	private Boolean createdFactory;
	private Integer flexibility;
	private Boolean isCoordinator;
	private Set<HolonElement> holonElements = new HashSet<HolonElement>(0);
	private Set<PowerLine> powerLines = new HashSet<PowerLine>(0);
	private Set<PowerSource> powerSources = new HashSet<PowerSource>(0); 
	private Set<Supplier> supplierProducers = new HashSet<Supplier>(0);
	private Set<Supplier> supplierConsumers = new HashSet<Supplier>(0);
	private BigDecimal coordinatorCompetency;
	private BigDecimal trustValue;
	
	public HolonObject(int id, EnergyState energyState, Holon holon,
			HolonObjectType holonObjectType, LatLng latLngByNeLocation,
			LatLng latLngBySwLocation, Boolean lineConnectedState,
			Integer consumption, Boolean canCommunicate,
			Boolean createdFactory, Integer flexibility, Boolean isCoordinator,
			Set<HolonElement> holonElements, Set<PowerLine> powerLines,
			Set<PowerSource> powerSources, Set<Supplier> supplierProducers,
			Set<Supplier> supplierConsumers, BigDecimal coordinatorCompetency,
			BigDecimal trustValue) {
		super();
		this.id = id;
		this.energyState = energyState;
		this.holon = holon;
		this.holonObjectType = holonObjectType;
		this.latLngByNeLocation = latLngByNeLocation;
		this.latLngBySwLocation = latLngBySwLocation;
		this.lineConnectedState = lineConnectedState;
		this.consumption = consumption;
		this.canCommunicate = canCommunicate;
		this.createdFactory = createdFactory;
		this.flexibility = flexibility;
		this.isCoordinator = isCoordinator;
		this.holonElements = holonElements;
		this.powerLines = powerLines;
		this.powerSources = powerSources;
		this.supplierProducers = supplierProducers;
		this.supplierConsumers = supplierConsumers;
		this.coordinatorCompetency = coordinatorCompetency;
		this.trustValue = trustValue;
	}

	public HolonObject() {
	}

	public HolonObject(int id) {
		this.id = id;
	}

	public Set<Supplier> getSupplierProducers() {
		return supplierProducers;
	}

	public void setSupplierProducers(Set<Supplier> supplierProducers) {
		this.supplierProducers = supplierProducers;
	}

	public Set<Supplier> getSupplierConsumers() {
		return supplierConsumers;
	}

	public void setSupplierConsumers(Set<Supplier> supplierConsumers) {
		this.supplierConsumers = supplierConsumers;
	}

	public Holon getHolon() {
		return holon;
	}

	public void setHolon(Holon holon) {
		this.holon = holon;
	}

	public Boolean getIsCoordinator() {
		return isCoordinator;
	}

	public void setIsCoordinator(Boolean isCoordinator) {
		this.isCoordinator = isCoordinator;
	}

	public Set<PowerSource> getPowerSources() {
		return powerSources;
	}

	public void setPowerSources(Set<PowerSource> powerSources) {
		this.powerSources = powerSources;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public EnergyState getEnergyState() {
		return this.energyState;
	}

	public void setEnergyState(EnergyState energyState) {
		this.energyState = energyState;
	}

	public HolonObjectType getHolonObjectType() {
		return this.holonObjectType;
	}

	public void setHolonObjectType(HolonObjectType holonObjectType) {
		this.holonObjectType = holonObjectType;
	}

	public LatLng getLatLngByNeLocation() {
		return this.latLngByNeLocation;
	}

	public void setLatLngByNeLocation(LatLng latLngByNeLocation) {
		this.latLngByNeLocation = latLngByNeLocation;
	}

	public LatLng getLatLngBySwLocation() {
		return this.latLngBySwLocation;
	}

	public void setLatLngBySwLocation(LatLng latLngBySwLocation) {
		this.latLngBySwLocation = latLngBySwLocation;
	}

	public Boolean getLineConnectedState() {
		return this.lineConnectedState;
	}

	public void setLineConnectedState(Boolean lineConnectedState) {
		this.lineConnectedState = lineConnectedState;
	}

	public Integer getConsumption() {
		return this.consumption;
	}

	public void setConsumption(Integer consumption) {
		this.consumption = consumption;
	}

	public Boolean getCanCommunicate() {
		return this.canCommunicate;
	}

	public void setCanCommunicate(Boolean canCommunicate) {
		this.canCommunicate = canCommunicate;
	}

	public Boolean getCreatedFactory() {
		return this.createdFactory;
	}

	public void setCreatedFactory(Boolean createdFactory) {
		this.createdFactory = createdFactory;
	}

	public Set<HolonElement> getHolonElements() {
		return this.holonElements;
	}

	public void setHolonElements(Set<HolonElement> holonElements) {
		this.holonElements = holonElements;
	}

	public Set<?> getPowerLines() {
		return this.powerLines;
	}

	public void setPowerLines(Set<PowerLine> powerLines) {
		this.powerLines = powerLines;
	}

	private int getProducerCount(HolonObject ho)
	{
		int count=0;
		
		Set<HolonElement> heSet = getHolonElements();
		Iterator<HolonElement> iter = heSet.iterator();
		while (iter.hasNext()) {
		    HolonElement he = (HolonElement) iter.next();
		    if(he.getHolonElementType().getProducer())
		    {
		    	count++;
		    }
		}
		return count;
		
	}

	@Override
	public int compareTo(Object obj) {
		int result=0;
		HolonObject ho2 = (HolonObject)(obj);
		result = (this.getHolonElements().size() < ho2.getHolonElements().size() ) ? -1: (this.getHolonElements().size() > ho2.getHolonElements().size() ) ? 1:0 ;
		if(result==0)
		{
			result = (getProducerCount(this) < getProducerCount(ho2) ) ? -1: (getProducerCount(this) > getProducerCount(ho2) ) ? 1:0 ;
		}
		return result;
	}

	public Integer getFlexibility() {
		return flexibility;
	}

	public void setFlexibility(Integer flexibility) {
		this.flexibility = flexibility;
	}
	public BigDecimal getCoordinatorCompetency() {
		return coordinatorCompetency;
	}

	public void setCoordinatorCompetency(BigDecimal coordinatorCompetency) {
		this.coordinatorCompetency = coordinatorCompetency;
	}

	public BigDecimal getTrustValue() {
		return trustValue;
	}

	public void setTrustValue(BigDecimal trustValue) {
		this.trustValue = trustValue;
	}

}
